# -*- coding=utf-8
'''
Created on 2015年7月31日

@author: zhaojiangang
'''
import unittest

from biz.mock import patch
from entity.hallbenefits_test import benefits_conf
from entity.hallstore_test import clientIdMap, item_conf, products_conf, \
    store_template_conf, store_default_conf
from entity.hallvip_test import vip_conf
from hall.entity import hallitem, hallvip, hallbenefits, hallshare, hallpromote
import poker.util.timestamp as pktimestamp
from test_base import HallTestMockContext

share_conf = {
    "shares":[
        {
            "shareId":100,
            "type":"weixin",
            "subType":"0",
            "desc":"我发现了一个好玩的游戏，快来陪我玩~还有免费金币可以领！",
            "tips":"现在分享即可获得金币奖励呦！",
            "title":"亲爱的小伙伴",
            "url":"http://3g.tuyoo.com/weixin/hallShareDizhu.html",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":1000}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":2,
            "desc":"来玩途游斗地主，输入我的推荐码\\${promoteCode}，一起拿红包，赢话费！",
            "title":"亲爱的小伙伴",
            "url":"http://3g.tuyoo.com/fenxiang/promotionCode.html?json=\\${promoteCode}",
            "typeId":"hall.share.promote",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":1000}
                ]
            },
            "bottomRewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":10000}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":4,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://wxddz.tuyoo.com/",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":5,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://360dj.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":6,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://360tu.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":7,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://360happy.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":8,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享残局斗地主即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://360win.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":9,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://qqdj.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":10,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://qqtu.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":11,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://qqhappy.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        },
        {
            "shareId":12,
            "type":"weixin",
            "subType":"0",
            "desc":"啦啦啦",
            "tips":"现在分享即可获得金币奖励！",
            "title":"飞机炸弹嗨翻天,还有话费送哦~",
            "url":"http://baidu.cjddz.tuyoo.com/index.php?stage=2&skin=grass",
            "typeId":"hall.share.url",
            "maxRewardCount":1,
            "rewardContent":{
                "typeId":"FixedContent",
                "items":[
                    {"itemId":"user:chip", "count":500}
                ]
            },
            "mail":"恭喜您获得\\${rewardContent}的分享奖励！"
        }
    ]
}

promote_conf = {
    "promotions":[
        {
            "promotionId":1,
            "displayName":"商城",
            "url":"${http_download}/hall/promote/imgs/store.png",
            "animate":1,
            "todotasks":[
                {"typeId":"hall.goto.shop", "subStore":"coin"}
            ]
        },
        {
            "promotionId":2,
            "displayName":"活动页面",
            "url":"http://icon.nipic.com/BannerPic/20150126/indexmedia/20150126161003.jpg",
            "animate":1,
            "todotasks":[
                {"typeId":"hall.goto.activity", "url":"http://TODO.html"}
            ]
        },
        {
            "promotionId":3,
            "displayName":"插件游戏跳转",
            "url":"http://icon.nipic.com/BannerPic/20150126/indexmedia/20150126161003.jpg",
            "animate":1,
            "todotasks":[
            ]
        },
        {
            "promotionId":4,
            "displayName":"首充礼包",
            "url":"${http_download}/hall/promote/imgs/firstrecharge.png",
            "animate":0,
            "todotasks":[
                {
                    "typeId":"todotask.firstRecharge",
                    "payOrder":{
                        "productId":"TY9999D0006001"
                    },
                     "title":"今天充值任意金额，可额外领取", 
                     "url":"${http_download}/hall/promote/imgs/first_recharge_content.png", 
                     "confirm": 1,
                     "confirmDesc":"对不起，您还不满足领取礼包的条件\n现在就购买\\${productName}(\\${productPrice}元)即可领取豪华大礼包！" 
                }
            ]
        },
        {
            "promotionId":5,
            "displayName":"VIP",
            "url":"${http_download}/hall/promote/imgs/vip.png",
            "animate":1,
            "todotasks":[
                {"typeId":"hall.goto.vip"}
            ]
        },
        {
            "promotionId":6,
            "displayName":"推荐分享",
            "url":"${http_download}/hall/promote/imgs/share.png",
            "animate":1,
            "todotasks":[
                {"typeId":"hall.goto.promote"}
            ]
        },
        {
            "promotionId":7,
            "displayName":"首充礼包奖励",
            "url":"${http_download}/hall/promote/imgs/firstrecharge.png",
            "animate":0,
            "todotasks":[
                {
                    "typeId":"todotask.firstRechargeReward",
                     "desc":"恭喜您获得首充奖励大礼包！",
                     "url":"${http_download}/hall/promote/imgs/first_recharge_content.png"
                }
            ]
        },
        {
            "promotionId":8,
            "displayName":"首充礼包",
            "url":"${http_download}/hall/promote/imgs/firstrecharge.png",
            "animate":0,
            "todotasks":[
                {
                    "typeId":"todotask.firstRecharge", 
                    "payOrder":{
                        "productId":"TY9999D0006003"
                    },
                    "title":"今天充值任意金额，可额外领取", 
                    "url":"${http_download}/hall/promote/imgs/first_recharge_content.png",
                    "confirm": 1,
                    "confirmDesc":"对不起，您还不满足领取礼包的条件\n现在就购买\\${productName}(\\${productPrice}元)即可领取豪华大礼包！" 
                }
            ]
        },
        {
            "promotionId":9,
            "displayName":"wifikey更多游戏",
            "url":"${http_download}/hall/promote/imgs/wifikey.png",
            "animate":1,
            "todotasks":[
                {"typeId":"hall.wifikey.promote"}
            ]
        },
        {
            "promotionId":10,
            "displayName":"首充礼包",
            "url":"${http_download}/hall/promote/imgs/firstrecharge.png",
            "animate":0,
            "todotasks":[
                {
                    "typeId":"todotask.firstRecharge", 
                    "payOrder":{
                        "productId":"TY9999D0006007"
                    }, 
                     "title":"今天充值任意金额，可额外领取", 
                     "url":"${http_download}/hall/promote/imgs/first_recharge_content.png",
                     "confirm": 1,
                     "confirmDesc":"对不起，您还不满足领取礼包的条件\n现在就购买\\${productName}(\\${productPrice}元)即可领取豪华大礼包！" 
                }
            ]
        },
        {
            "promotionId":11,
            "displayName":"首充礼包",
            "url":"${http_download}/hall/promote/imgs/firstrecharge.png",
            "animate":0,
            "todotasks":[
                {
                    "templateName":"firstRecharge"
                }
            ]
        },
        {
            "promotionId":12,
            "displayName":"首充礼包",
            "url":"${http_download}/hall/promote/imgs/firstrecharge.png",
            "animate":0,
            "todotasks":[
                {
                    "templateName":"firstRecharge"
                }
            ]
        }
    ],
    "templates":[
        {
            "name":"template.1",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":1,
                            "conditions":[]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":6,
                            "conditions":[]
                        }
                    ]                
                },
                {
                    "pos":3,
                    "promotes":[
                        {
                            "promotionId":4,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.online.beta",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":4,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.mj",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":3,
                    "promotes":[
                        {
                            "promotionId":4,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.mj.ios",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":3,
                    "promotes":[
                        {
                            "promotionId":10,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.3_5_02",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":4,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.3_5_02.ios",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":8,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.3_5_02_wifikey",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":4,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":3,
                    "promotes":[
                        {
                            "promotionId":9,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.3_7",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":11,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"template.3_7.ios",
            "positions":[
                {
                    "pos":1,
                    "promotes":[
                        {
                            "promotionId":8,
                            "conditions":[
                                {"typeId":"user.cond.unFirstRecharged"}
                            ]
                        },
                        {
                            "promotionId":7,
                            "conditions":[
                                {"typeId":"user.cond.unGotFirstRechargeReward"}
                            ]
                        },
                        {
                            "promotionId":1,
                            "conditions":[
                            ]
                        }
                    ]
                },
                {
                    "pos":2,
                    "promotes":[
                        {
                            "promotionId":5,
                            "conditions":[
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}


class TestHallShare(unittest.TestCase):
    userId = 10001
    gameId = 6
    clientId = 'IOS_3.70_360.360.0-hall6.360.day'
    testContext = HallTestMockContext()
    
    def setUp(self):
        self.testContext.startMock()
        self.testContext.confDB.setConf('poker:map.clientid', clientIdMap)
        self.testContext.configure.setJson('game:9999:map.clientid', clientIdMap, 0)
        self.testContext.configure.setJson('poker:map.clientid', clientIdMap, 0)
        self.testContext.configure.setJson('game:9999:item', item_conf, 0)
        self.testContext.configure.setJson('game:9999:products', products_conf, 0)
        self.testContext.configure.setJson('game:9999:store', store_template_conf, 0)
        self.testContext.configure.setJson('game:9999:store', store_default_conf, clientIdMap[self.clientId])
        self.testContext.configure.setJson('game:9999:vip', vip_conf, 0)
        self.testContext.configure.setJson('game:9999:benefits', benefits_conf, 0)
        self.testContext.configure.setJson('game:9999:share', share_conf, 0)
        self.testContext.configure.setJson('game:9999:promote', promote_conf, 0)
        self.testContext.configure.setJson('game:9999:promote',
                                           {"template": "template.3_7.ios"}, 13232)
        self.timestamp = pktimestamp.getCurrentTimestamp()
        self.pktimestampPatcher = patch('poker.util.timestamp.getCurrentTimestamp', self.getCurrentTimestamp)
        self.pktimestampPatcher.start()
        
        hallitem._initialize()
        hallvip._initialize()
        hallbenefits._initialize()
        hallshare._initialize()
        hallpromote._initialize()
        
    def tearDown(self):
        self.pktimestampPatcher.stop()
        self.testContext.stopMock()
        
    def getCurrentTimestamp(self):
        return self.timestamp
    
    def testLoad(self):
        promotes = hallpromote.getPromotes(6, self.userId, self.clientId, self.timestamp)
        print [(promote.promotion.promotionId, promote.position.pos) for promote in promotes]
            
if __name__ == '__main__':
    unittest.main()


