# -*- coding=utf-8


class TYActivityType(object):
    """
    活动ID枚举
    """
    ACTIVITY_WELFARE = 1
    ACTIVITY_PLAYGAME_GIFT = 2
    ACTIVITY_EXCHANGE_CODE = 3
    ACTIVITY_RAFFLE = 4
    ACTIVITY_FIRST_CHARGE = 5
    ACTIVITY_NOTICE_IMG = 6
    ACTIVITY_VIP_MATCH = 7
    ACTIVITY_DDZ_MATCH = 8
    ACTIVITY_FANFANLE = 11
    ACTIVITY_SALE = 13
    ACTIVITY_MATCH_QUIZ = 6004
    ACTIVITY_SHARE_CLICK = 9999001
    ACTIVITY_CREDIT_EXCHANGE = 9999002
    ACTIVITY_NEW_FRIEND_INVITE = 9999003
    ACTIVITY_ITEM_EXCHANGE = 9999004
