# -*- coding=utf-8
'''
Created on 2015年6月30日

@author: zhaojiangang
'''
import unittest

from entity.hallstore_test import clientIdMap, item_conf, products_conf, \
    store_template_conf, store_default_conf
from entity.hallvip_test import vip_conf
import freetime.util.log as ftlog
from hall.entity import hallvip, hallitem, hallranking
from test_base import HallTestMockContext


ranking_conf = {
    "list":[
        {
            "rankingId":"110007002",
            "name":"雀神榜",
            "desc":"本周雀神分排行！",
            "totalNumber":0,
            "gameIds":[
                7
            ],
            "inputType":"dashifen",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_7.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0_qs.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1_qs.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2_qs.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "keepNumbers":100,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110000001",
            "name":"财富榜",
            "desc":"金币总排行，高富帅和白富美的聚集地！",
            "totalNumber":0,
            "gameIds":[
                0
            ],
            "inputType":"chip",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/icon_gold.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":50,
            "totalN":100,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110000003",
            "name":"魅力榜",
            "desc":"魅力值总排行，人气之星，一呼百应！",
            "totalNumber":0,
            "gameIds":[
                0
            ],
            "inputType":"charm",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/charm.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":50,
            "totalN":100,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100008004",
            "name":"总奖金周榜",
            "desc":"本周赢取总奖金排行，人人都是大赢家！",
            "totalNumber":0,
            "gameIds":[
                8
            ],
            "inputType":"winChip",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/icon_gold.png"
            },
            "rankDesc":{
                "in":"您在\\${rankName}的排名是：\\${rank}",
                "out":"暂未进入\\${rankName}，加油哦！"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[
                {
                    "start":1,
                    "end":1,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"7天牌神之翼+100万金币",
                        "items":[
                            {
                                "itemId":"item:4124",
                                "count":7
                            },
                            {
                                "itemId":"user:chip",
                                "count":1000000
                            }
                        ]
                    }
                },
                {
                    "start":2,
                    "end":3,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"7天荣耀之翼+50万金币",
                        "items":[
                            {
                                "itemId":"item:4126",
                                "count":7
                            },
                            {
                                "itemId":"user:chip",
                                "count":500000
                            }
                        ]
                    }
                },
                {
                    "start":4,
                    "end":10,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"20万金币",
                        "items":[
                            {
                                "itemId":"user:chip",
                                "count":200000
                            }
                        ]
                    }
                }
            ]
        },
        {
            "rankingId":"100008005",
            "name":"PK榜",
            "desc":"今日PK榜",
            "totalNumber":0,
            "gameIds":[
                8
            ],
            "inputType":"pk",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/pk.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100008106",
            "name":"翻牌赢钱榜",
            "desc":"每日翻牌赢钱榜",
            "totalNumber":0,
            "gameIds":[
                8
            ],
            "inputType":"dzfcWinChip",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/icon_gold.png"
            },
            "rankDesc":{
                "in":"您在\\${rankName}的排名是：\\${rank}",
                "out":"暂未进入\\${rankName}，加油哦！"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":30,
            "totalN":100,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100001002",
            "name":"金花王",
            "desc":"今日金花榜",
            "totalNumber":0,
            "gameIds":[
                3
            ],
            "inputType":"dashifen",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_3.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100006002",
            "name":"大师榜",
            "desc":"今日大师分排行，谁的水平高，来斗斗看吧！",
            "totalNumber":0,
            "gameIds":[
                6
            ],
            "inputType":"dashifen",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_6.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100010002",
            "name":"牛掰榜",
            "desc":"1、今日实时榜单，24点发放奖励！\n2、每天参加游戏10局以上，即有机会上榜得奖励！",
            "totalNumber":0,
            "gameIds":[
                10
            ],
            "inputType":"dashifen",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/ranking_nothing.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/nbf_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/nbf_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/nbf_2.png"
                },
                {
                    "rank":3,
                    "pic":"${http_download}/hall/rank/nbf_3.png"
                },
                {
                    "rank":4,
                    "pic":"${http_download}/hall/rank/nbf_4.png"
                },
                {
                    "rank":5,
                    "pic":"${http_download}/hall/rank/nbf_5.png"
                },
                {
                    "rank":6,
                    "pic":"${http_download}/hall/rank/nbf_6.png"
                },
                {
                    "rank":7,
                    "pic":"${http_download}/hall/rank/nbf_7.png"
                },
                {
                    "rank":8,
                    "pic":"${http_download}/hall/rank/nbf_8.png"
                },
                {
                    "rank":9,
                    "pic":"${http_download}/hall/rank/nbf_9.png"
                }
            ],
            "topN":50,
            "totalN":50,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[
                {
                    "start":1,
                    "end":1,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"1天牌神之翼",
                        "items":[
                            {
                                "itemId":"item:4124",
                                "count":1
                            }
                        ]
                    }
                },
                {
                    "start":2,
                    "end":10,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"1天荣耀之翼",
                        "items":[
                            {
                                "itemId":"item:4126",
                                "count":1
                            }
                        ]
                    }
                }
            ]
        },
        {
            "rankingId":"100010001",
            "name":"财富榜",
            "desc":"1、今日实时榜单，24点发放奖励！\n2、每天参加游戏10局以上，即有机会上榜得奖励！",
            "totalNumber":0,
            "gameIds":[
                10
            ],
            "inputType":"chip",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/icon_gold.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/nbf_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/nbf_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/nbf_2.png"
                },
                {
                    "rank":3,
                    "pic":"${http_download}/hall/rank/nbf_3.png"
                },
                {
                    "rank":4,
                    "pic":"${http_download}/hall/rank/nbf_4.png"
                },
                {
                    "rank":5,
                    "pic":"${http_download}/hall/rank/nbf_5.png"
                },
                {
                    "rank":6,
                    "pic":"${http_download}/hall/rank/nbf_6.png"
                },
                {
                    "rank":7,
                    "pic":"${http_download}/hall/rank/nbf_7.png"
                },
                {
                    "rank":8,
                    "pic":"${http_download}/hall/rank/nbf_8.png"
                },
                {
                    "rank":9,
                    "pic":"${http_download}/hall/rank/nbf_9.png"
                }
            ],
            "topN":50,
            "totalN":50,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[
                {
                    "start":1,
                    "end":1,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"1天牌神之翼",
                        "items":[
                            {
                                "itemId":"item:4124",
                                "count":1
                            }
                        ]
                    }
                },
                {
                    "start":2,
                    "end":10,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"1天荣耀之翼",
                        "items":[
                            {
                                "itemId":"item:4126",
                                "count":1
                            }
                        ]
                    }
                }
            ]
        },
        {
            "rankingId":"110018002",
            "name":"金顺榜",
            "desc":"今日金顺榜排行",
            "totalNumber":0,
            "gameIds":[
                18
            ],
            "inputType":"dashifen",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_18.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110008002",
            "name":"鲨鱼分周榜",
            "desc":"本周获得鲨鱼分排行，走向牌神之路！",
            "totalNumber":0,
            "gameIds":[
                8
            ],
            "inputType":"dashifen",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[
                {
                    "start":1,
                    "end":1,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"7天牌神之翼+100万金币",
                        "items":[
                            {
                                "itemId":"item:4124",
                                "count":7
                            },
                            {
                                "itemId":"user:chip",
                                "count":1000000
                            }
                        ]
                    }
                },
                {
                    "start":2,
                    "end":3,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"7天荣耀之翼+50万金币",
                        "items":[
                            {
                                "itemId":"item:4126",
                                "count":7
                            },
                            {
                                "itemId":"user:chip",
                                "count":500000
                            }
                        ]
                    }
                },
                {
                    "start":4,
                    "end":10,
                    "rewardContent":{
                        "typeId":"FixedContent",
                        "desc":"20万金币",
                        "items":[
                            {
                                "itemId":"user:chip",
                                "count":200000
                            }
                        ]
                    }
                }
            ]
        },
        {
            "rankingId":"100015007",
            "name":"范特西榜",
            "desc":"今日范特西次数榜",
            "totalNumber":0,
            "gameIds":[
                15
            ],
            "inputType":"fantasy",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":10,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110015007",
            "name":"范特西榜",
            "desc":"范特西次数周榜",
            "totalNumber":0,
            "gameIds":[
                15
            ],
            "inputType":"fantasy",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100015008",
            "name":"最大手牌榜",
            "desc":"今日最大手牌榜",
            "totalNumber":0,
            "gameIds":[
                15
            ],
            "inputType":"topHandsScore",
            "scoreType":{
                "typeId":"max"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":10,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110015008",
            "name":"最大手牌榜",
            "desc":"最大手牌周榜",
            "totalNumber":0,
            "gameIds":[
                15
            ],
            "inputType":"topHandsScore",
            "scoreType":{
                "typeId":"max"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"100015009",
            "name":"赛事积分榜",
            "desc":"今日赛事积分榜",
            "totalNumber":0,
            "gameIds":[
                15
            ],
            "inputType":"opi",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":10,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"day"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110015009",
            "name":"赛事积分榜",
            "desc":"赛事积分周榜",
            "totalNumber":0,
            "gameIds":[
                15
            ],
            "inputType":"opi",
            "scoreType":{
                "typeId":"incr"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_8.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2.png"
                }
            ],
            "topN":100,
            "totalN":500,
            "cacheTimes":0,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        },
        {
            "rankingId":"110003010",
            "name":"中国象棋积分榜",
            "desc":"本周中国象棋积分排行！",
            "totalNumber":0,
            "gameIds":[
                3
            ],
            "inputType":"jifen",
            "scoreType":{
                "typeId":"normal"
            },
            "type":{
                "typeName":"name_head_number",
                "rankValueIcon":"${http_download}/hall/rank/dashifen_7.png"
            },
            "rankPics":[
                {
                    "rank":0,
                    "pic":"${http_download}/hall/rank/rank_0_qs.png"
                },
                {
                    "rank":1,
                    "pic":"${http_download}/hall/rank/rank_1_qs.png"
                },
                {
                    "rank":2,
                    "pic":"${http_download}/hall/rank/rank_2_qs.png"
                }
            ],
            "topN":10,
            "totalN":15,
            "cacheTimes":0,
            "keepNumbers":100,
            "cycle":{
                "typeId":"week"
            },
            "rankRewardList":[]
        }
    ]
}

class TestVIP(unittest.TestCase):
    userId = 10001
    gameId = 6
    clientId = 'IOS_3.6_momo'
    testContext = HallTestMockContext()
    
    def setUp(self):
        self.testContext.startMock()
        self.testContext.configure.setJson('game:9999:map.clientid', clientIdMap, 0)
        self.testContext.configure.setJson('game:9999:item', item_conf, 0)
        self.testContext.configure.setJson('game:9999:products', products_conf, 0)
        self.testContext.configure.setJson('game:9999:store', store_template_conf, 0)
        self.testContext.configure.setJson('game:9999:store', store_default_conf, clientIdMap[self.clientId])
        self.testContext.configure.setJson('game:9999:vip', vip_conf, 0)
        self.testContext.configure.setJson('game:9999:ranking', ranking_conf, 0)
        hallitem._initialize()
        hallvip._initialize()
        hallranking._initialize()
        
    def tearDown(self):
        self.testContext.stopMock()
        
    def testLoad(self):
        rankingDefines = hallranking.rankingSystem.getRankingDefines()
        rankingIds = [rd.rankingId for rd in rankingDefines]
        ftlog.info(rankingIds)
        
        hallranking.rankingSystem.setUserByInputType(self.gameId, 'chip', self.userId, 100)
        
if __name__ == '__main__':
    unittest.main()

